name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.14-bookworm-slim
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build package distributions
        run: uv build

      - name: Generate PEP 740 attestations
        uses: astral-sh/attest-action@f589a42a7efb6fe400b4f400de60b4bc90390027 # v0.0.6

      - name: Publish
        run: uv publish

  release:
    name: Create Github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
